### ISSUE TITLE
Python3.5 

### ISSUE THREAD

**Issue by Sumukh** [brianhou/bombast#1]
```
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ast.py", line 300, in generic_visit
    value = self.visit(value)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ast.py", line 245, in visit
    return visitor(node)
  File "/Users/sumukh/Dropbox/CS61A/b61a/lib/python3.5/site-packages/bombast/__init__.py", line 126, in visit_ClassDef
    node.keywords, node.starargs, node.kwargs,
AttributeError: 'ClassDef' object has no attribute 'starargs'
```

**Comment by brianhou** [comment]
It seems that the ast module might change with every minor version. [This](https://docs.python.org/3/library/ast.html#ast.AST._fields) might help.

The specific issue seems that Python 3.4 has `starargs` and `kwargs`, and that Python 3.5 doesn't.

**Comment by knrafto** [comment]
Bump, this is pretty annoying. Perhaps 61a should move to a different python obfuscator?

**Comment by brianhou** [comment]
Sorry, I haven't had time to think of a proper fix to figure out how many (and which) fields should be included, regardless of the version of the Python ast module / grammar.

A different Python obfuscator could work. A really bad temporary hack is to edit `env/lib/python3.5/site-packages/bombast/__init__.py` line 126 to only contain `node.keywords`.

**Comment by brianhou** [comment]
I think 3bc967a039424d06805e0f56570456817acdfea0 fixes this, but I've had to use Travis' Python 3.5 install to check.
