### ISSUE TITLE
Python 3.8

### ISSUE THREAD

**Issue by mehrdadn** [brianhou/bombast#2]
Python 3.8 has inserted a new argument in the beginning of `ast.arguments`'s constructor, breaking bombast. Demo:

    $ python3.7 -c "import ast; print(ast.arguments([]).args)"
    $ python3.8 -c "import ast; print(ast.arguments([]).args)"

Reason:

    $ python3.7 -c "import ast; print(ast.arguments._fields)"
    ('args', 'vararg', 'kwonlyargs', 'kw_defaults', 'kwarg', 'defaults')
    $ python3.8 -c "import ast; print(ast.arguments._fields)"
    ('posonlyargs', 'args', 'vararg', 'kwonlyargs', 'kw_defaults', 'kwarg', 'defaults')

[Related](https://github.com/python/cpython/search?q=posonlyargs+is%3Apr&type=Issues):

- python/cpython#12701
- python/cpython#14139
- python/cpython#14778
- python/cpython#14779

**Comment by brianhou** [comment]
Thanks for the report! I'm happy to merge any of yours or @kavigupta's PRs to fix this, just let me know.

**Comment by mehrdadn** [comment]
I think @kavigupta switched to our own fork of the repo, but in any case, feel free to merge mine (#4)! I just reopened it.

@kavigupta is it good to merge your changes too?

**Comment by kavigupta** [comment]
I had changes that probably span a couple PRs. I'll organize them then link them here
